### PR TITLE
l10n: Replace the apostrophe with double quotation

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Transifex.

### CODE REVIEW

**Comment by DecaTec** [comment]
Please use Trabnsifex in order to change translated strings. This is then automatically merged into the repo.
Thanks!

**Comment by Valdnet** [comment]
> Please use Trabnsifex in order to change translated strings.

@DecaTec But this is the changed string for the English text string that is retrieved by Transifex. This should be changed in this PR to be updated for translators in Transifex.

**Comment by DecaTec** [comment]
This is only the quotation marks, right?
For now, I would leave it as it is, I think we need a review of the string to be translated when the app is ported for NC 18+.

**Comment by Valdnet** [comment]
> This is only the quotation marks, right?

Only, or as much as. It depends on how you look at it 😉.

It matters to the translator. However, to be consistent with the entire NC instance, this should be changed. But the decision is yours.

**Pull request closed without merging**
